# Generated by Django 6.0.3 on 2026-04-05 17:36

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('source_type', models.TextField(choices=[('csv_upload', 'CSV Upload'), ('webhook', 'Webhook'), ('rss_pull', 'RSS Pull'), ('api_pull', 'API Pull')])),
                ('config', models.JSONField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='core.tenant')),
            ],
            options={
                'db_table': 'sources',
            },
        ),
        migrations.CreateModel(
            name='RoutingConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('confidence_threshold', models.FloatField(default=0.85)),
                ('items_below_threshold_action', models.TextField(choices=[('flag', 'Flag'), ('skip_ai', 'Skip AI')], default='flag')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_configs', to='core.tenant')),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='routing_config', to='ingestion.source')),
            ],
            options={
                'db_table': 'routing_config',
            },
        ),
        migrations.CreateModel(
            name='FeedbackItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.TextField(blank=True, null=True)),
                ('content', models.TextField()),
                ('author', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('received_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sentiment', models.TextField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral'), ('mixed', 'Mixed')], null=True)),
                ('sentiment_confidence', models.FloatField(blank=True, null=True)),
                ('urgency', models.TextField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], null=True)),
                ('themes', models.JSONField(blank=True, null=True)),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_items', to='core.tenant')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_items', to='ingestion.source')),
            ],
            options={
                'db_table': 'feedback_items',
                'indexes': [models.Index(fields=['tenant'], name='idx_feedback_tenant'), models.Index(fields=['source'], name='idx_feedback_source'), models.Index(fields=['tenant', 'sentiment'], name='idx_feedback_sentiment'), models.Index(fields=['tenant', 'received_at'], name='idx_feedback_received'), models.Index(condition=models.Q(('processed_at__isnull', True)), fields=['tenant'], name='idx_feedback_unprocessed'), pgvector.django.indexes.IvfflatIndex(fields=['embedding'], lists=100, name='idx_feedback_embedding', opclasses=['vector_cosine_ops'])],
            },
        ),
    ]
