# Generated by Django 6.0.3 on 2026-04-05 17:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.TextField()),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('source', models.TextField(choices=[('manual', 'Manual'), ('discovered', 'Discovered')], default='manual')),
                ('first_seen_at', models.DateTimeField(blank=True, null=True)),
                ('item_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='themes.theme')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='core.tenant')),
            ],
            options={
                'db_table': 'themes',
                'constraints': [models.UniqueConstraint(fields=('tenant', 'slug'), name='uniq_theme_tenant_slug')],
            },
        ),
    ]
