# Generated by Django 6.0.3 on 2026-04-21 18:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.TextField(choices=[('weekly_outlook', 'Weekly Outlook')])),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.TextField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending')),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('polished_content', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('task_id', models.TextField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.tenant')),
            ],
            options={
                'db_table': 'reports',
            },
        ),
        migrations.CreateModel(
            name='ReportSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_type', models.TextField(choices=[('exec_summary', 'Executive Summary'), ('whats_changed', "What's Changed"), ('whats_working', "What's Working"), ('needs_attention', 'Needs Attention'), ('recommendations', 'Top Recommendations'), ('decisions_made', 'Decisions This Week')])),
                ('order', models.IntegerField()),
                ('raw_content', models.JSONField()),
                ('polished_content', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='reports.report')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_sections', to='core.tenant')),
            ],
            options={
                'db_table': 'report_sections',
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['tenant', '-created_at'], name='idx_reports_tenant'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(fields=('tenant', 'report_type', 'period_start', 'period_end'), name='uq_report_tenant_type_period'),
        ),
        migrations.AddConstraint(
            model_name='reportsection',
            constraint=models.UniqueConstraint(fields=('report', 'section_type'), name='uq_section_report_type'),
        ),
    ]
