# Generated by Django 6.0.3 on 2026-04-05 17:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.IntegerField()),
                ('prompt_template', models.TextField()),
                ('few_shot_examples', models.JSONField(blank=True, null=True)),
                ('accuracy_at_creation', models.FloatField(blank=True, null=True)),
                ('accuracy_current', models.FloatField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_versions', to='core.tenant')),
            ],
            options={
                'db_table': 'prompt_versions',
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('problem_statement', models.TextField()),
                ('proposed_action', models.TextField()),
                ('impact_score', models.FloatField()),
                ('effort_score', models.FloatField()),
                ('confidence', models.FloatField()),
                ('priority_score', models.FloatField()),
                ('decision_owner', models.TextField(blank=True, null=True)),
                ('status', models.TextField(choices=[('proposed', 'Proposed'), ('accepted', 'Accepted'), ('dismissed', 'Dismissed'), ('needs_more_evidence', 'Needs More Evidence')], default='proposed')),
                ('rationale', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='core.tenant')),
            ],
            options={
                'db_table': 'recommendations',
            },
        ),
        migrations.CreateModel(
            name='RecommendationEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evidence_weight', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feedback_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_evidence', to='ingestion.feedbackitem')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='analysis.recommendation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_evidence', to='core.tenant')),
            ],
            options={
                'db_table': 'recommendation_evidence',
            },
        ),
        migrations.CreateModel(
            name='RecommendationOutcome',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('measured_at', models.DateField()),
                ('metric_name', models.TextField()),
                ('baseline_value', models.FloatField()),
                ('current_value', models.FloatField()),
                ('delta', models.FloatField()),
                ('interpretation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='analysis.recommendation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_outcomes', to='core.tenant')),
            ],
            options={
                'db_table': 'recommendation_outcomes',
            },
        ),
        migrations.CreateModel(
            name='Correction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_corrected', models.TextField(choices=[('sentiment', 'Sentiment'), ('themes', 'Themes'), ('urgency', 'Urgency')])),
                ('ai_value', models.JSONField()),
                ('human_value', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feedback_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='ingestion.feedbackitem')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='core.tenant')),
            ],
            options={
                'db_table': 'corrections',
                'indexes': [models.Index(fields=['tenant', 'created_at'], name='idx_corrections_tenant')],
            },
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['tenant', 'status', '-created_at'], name='idx_reco_tenant_status'),
        ),
        migrations.AddIndex(
            model_name='recommendationevidence',
            index=models.Index(fields=['recommendation'], name='idx_reco_ev_reco'),
        ),
        migrations.AddIndex(
            model_name='recommendationoutcome',
            index=models.Index(fields=['recommendation', '-measured_at'], name='idx_reco_out_reco'),
        ),
    ]
