# Generated by Django 6.0.3 on 2026-04-23 02:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_recommendationevidence_selection_reason'),
        ('core', '0001_initial'),
        ('ingestion', '0002_feedbackitem_source_external_id_uniq'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldSetItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gold_sentiment', models.TextField()),
                ('gold_urgency', models.TextField()),
                ('gold_themes', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feedback_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gold_set_items', to='ingestion.feedbackitem')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gold_set_items', to='core.tenant')),
            ],
            options={
                'db_table': 'gold_set_items',
                'indexes': [models.Index(fields=['tenant'], name='idx_goldset_tenant')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'feedback_item'), name='uq_goldset_tenant_item')],
            },
        ),
    ]
