# Generated by Django 6.0.3 on 2026-04-23 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_goldsetitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptversion',
            name='regression_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
