# Generated by Django 6.0.3 on 2026-04-23 02:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_promptversion_regression_note'),
        ('core', '0001_initial'),
        ('ingestion', '0002_feedbackitem_source_external_id_uniq'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectionDisagreement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_corrected', models.TextField(choices=[('sentiment', 'Sentiment'), ('themes', 'Themes'), ('urgency', 'Urgency')])),
                ('correction_ids', models.JSONField()),
                ('resolution_status', models.TextField(choices=[('pending', 'Pending'), ('resolved', 'Resolved')], default='pending')),
                ('resolved_value', models.JSONField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feedback_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correction_disagreements', to='ingestion.feedbackitem')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correction_disagreements', to='core.tenant')),
            ],
            options={
                'db_table': 'correction_disagreements',
                'indexes': [models.Index(fields=['tenant', 'resolution_status'], name='idx_disagree_tenant_status')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'feedback_item', 'field_corrected'), name='uq_disagree_tenant_item_field')],
            },
        ),
    ]
