# Generated by Django 6.0.3 on 2026-04-23 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_correctiondisagreement'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='recommendationoutcome',
            constraint=models.UniqueConstraint(fields=('recommendation', 'metric_name', 'measured_at'), name='uq_reco_outcome_rec_metric_date'),
        ),
    ]
