# Generated by Django 6.0.3 on 2026-04-05 17:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.TextField(choices=[('volume_spike', 'Volume Spike'), ('sentiment_shift', 'Sentiment Shift'), ('new_theme', 'New Theme'), ('urgency_surge', 'Urgency Surge')])),
                ('severity', models.TextField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')])),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.tenant')),
            ],
            options={
                'db_table': 'alerts',
                'indexes': [models.Index(fields=['tenant', '-created_at'], name='idx_alerts_tenant')],
            },
        ),
        migrations.CreateModel(
            name='TrendSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot_date', models.DateField()),
                ('metrics', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trend_snapshots', to='core.tenant')),
            ],
            options={
                'db_table': 'trend_snapshots',
                'constraints': [models.UniqueConstraint(fields=('tenant', 'snapshot_date'), name='uniq_trend_snapshot_tenant_date')],
            },
        ),
    ]
